package aerialarts.model;
// default package
// Generated Apr 10, 2016 8:48:13 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "cinema")
public class Booking implements java.io.Serializable {

	public static final int STATUS__BOOKED = 1;
	public static final int STATUS__BOOKED_CANCELED = 2;
	
	
	private Integer id;
	private CinemaUser cinemaUser;
	private CinemaShow cinemaShow;
	private int status;
	private String description;

	public Booking() {
	}

	public Booking(CinemaUser cinemaUser, CinemaShow cinemaShow, int status) {
		this.cinemaUser = cinemaUser;
		this.cinemaShow = cinemaShow;
		this.status = status;
	}

	public Booking(CinemaUser cinemaUser, CinemaShow cinemaShow, int status, String description) {
		this.cinemaUser = cinemaUser;
		this.cinemaShow = cinemaShow;
		this.status = status;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_user_id", nullable = false)
	public CinemaUser getCinemaUser() {
		return this.cinemaUser;
	}

	public void setCinemaUser(CinemaUser cinemaUser) {
		this.cinemaUser = cinemaUser;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_show_id", nullable = false)
	public CinemaShow getCinemaShow() {
		return this.cinemaShow;
	}

	public void setCinemaShow(CinemaShow cinemaShow) {
		this.cinemaShow = cinemaShow;
	}

	@Column(name = "status", nullable = false)
	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}