package aerialarts.model;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.commons.lang.builder.ToStringBuilder;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * CinemaShow generated by hbm2java
 */
@Entity
@Table(name = "cinema_show", catalog = "cinema")
public class CinemaShow implements java.io.Serializable {

	private Integer id;
	private Movie movie;
	
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	private Date showTime;
	
	private boolean active;

	private int numberOfSeat;
	private String description;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public CinemaShow() {
	}

	public CinemaShow(Movie movie, boolean active, int numberOfSeat) {
		this.movie = movie;
		this.active = active;
		this.numberOfSeat = numberOfSeat;
	}

	public CinemaShow(Movie movie, boolean active, int numberOfSeat, String description, Set<Booking> bookings) {
		this.movie = movie;
		this.active = active;
		this.numberOfSeat = numberOfSeat;
		this.description = description;
		this.bookings = bookings;
	}

	@Override
	public String toString() {

		return ToStringBuilder.reflectionToString(this);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false) 
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}
	
	@Column(name = "show_time", nullable = false)
	public Date getShowTime() {
		return showTime;
	}

	public void setShowTime(Date showTime) {
		this.showTime = showTime;
	}
	
	@Column(name = "active", nullable = false)
	public boolean isActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	@Column(name = "number_of_seat", nullable = false)
	public int getNumberOfSeat() {
		return this.numberOfSeat;
	}

	public void setNumberOfSeat(int numberOfSeat) {
		this.numberOfSeat = numberOfSeat;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}