package aerialarts.model;
// default package
// Generated Apr 10, 2016 8:48:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie", catalog = "cinema")
public class Movie implements java.io.Serializable {

	private Integer id;
	private String name;
	
	@JsonFormat(pattern="yyyy-MM-dd")
	private Date releasedDate;
	private String description;
	private Set<CinemaShow> cinemaShows = new HashSet<CinemaShow>(0);

	public Movie() {
	}

	public Movie(String name, Date releasedDate, String description, Set<CinemaShow> cinemaShows) {
		this.name = name;
		this.releasedDate = releasedDate;
		this.description = description;
		this.cinemaShows = cinemaShows;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", length = 35)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "released_date", length = 19)
	public Date getReleasedDate() {
		return this.releasedDate;
	}

	public void setReleasedDate(Date releasedDate) {
		this.releasedDate = releasedDate;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<CinemaShow> getCinemaShows() {
		return this.cinemaShows;
	}

	public void setCinemaShows(Set<CinemaShow> cinemaShows) {
		this.cinemaShows = cinemaShows;
	}

}