package aerialarts.model;
// default package
// Generated Apr 10, 2016 8:48:13 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Role generated by hbm2java
 */
@Entity
public class Role implements java.io.Serializable {

	public static final Integer ROLE_ADMIN = 1;
	public static final Integer ROLE_USER = 2;
	
	private Integer id;
	private String name;
	private String description;
	
	
	private Set<CinemaUser> cinemaUsers = new HashSet<CinemaUser>(0);

	public Role() {
	}

	public Role(String name) {
		this.name = name;
	}

	public Role(String name, String description, Set<CinemaUser> cinemaUsers) {
		this.name = name;
		this.description = description;
		this.cinemaUsers = cinemaUsers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 25)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role" )
	public Set<CinemaUser> getCinemaUsers() {
		return this.cinemaUsers;
	}

	
	public void setCinemaUsers(Set<CinemaUser> cinemaUsers) {
		this.cinemaUsers = cinemaUsers;
	}

	@Override
	public String toString() {
		// TODO Auto-generated method stub
		return super.toString();
	}

}